FROM ${IMG_NAME}

RUN useradd docker && \
    mkdir -p /home/docker && \
    chown docker:docker /home/docker

USER docker

COPY *.ulf /home/docker/${IMG_TAG}.ulf

RUN cd /home/docker && \
    /opt/unity/Editor/Unity \
        -batchmode -nographics -quit -silent-crashes \
        -manualLicenseFile /home/docker/${IMG_TAG}.ulf || :
